apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
type: Opaque
data:
  password:
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-pastebin-credentials
type: Opaque
data:
  username:
  password:
