apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy volatile-lru
    requirepass <rootpw>
    user pastebin on +get +set +del ~pastebin:* ><usrpw>
