#!/bin/bash

set -xe

cd "$(dirname "$0")"

source .venv/bin/activate

source config.sh

python -c "import src.object_store as os; import asyncio; asyncio.run(os.get_text('fe64724c-cce8-4071-9f66-48c95ba1368d'))"
