apiVersion: batch/v1
kind: CronJob
metadata:
  name: pastebin-cleanup-expired-texts
  labels:
    app.kubernetes.io/name: pastebin-cleanup-expired-texts
    app.kubernetes.io/component: web
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: pastebin-cleanup-expired-texts
        app.kubernetes.io/component: web
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: pastebin-cleanup-expired-texts
            app.kubernetes.io/component: web
        spec:
          restartPolicy: OnFailure
          containers:
            - name: pastebin-cleanup-expired-texts
              image: jschnab/pastebin:async-prod
              imagePullPolicy: Always
              command: ["/bin/sh"]
              args: ["-c", "./run_cleanup"]
              env:
              - name: MYPASTEBIN_S3_BUCKET
                valueFrom:
                  configMapKeyRef:
                    name: pastebin-config
                    key: s3_bucket
              - name: MYPASTEBIN_DB_HOST
                valueFrom:
                  configMapKeyRef:
                    name: pastebin-config
                    key: db_host
              - name: MYPASTEBIN_DB_PORT
                valueFrom:
                  configMapKeyRef:
                    name: pastebin-config
                    key: db_port
              - name: MYPASTEBIN_DB_DATABASE
                valueFrom:
                  configMapKeyRef:
                    name: pastebin-config
                    key: db_database
              - name: MYPASTEBIN_DB_USER
                valueFrom:
                  secretKeyRef:
                    name: mariadb-pastebin-credentials
                    key: username
              - name: MYPASTEBIN_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mariadb-pastebin-credentials
                    key: password
              - name: MYPASTEBIN_URL
                valueFrom:
                  configMapKeyRef:
                    name: pastebin-config
                    key: app_url
              - name: MYPASTEBIN_CACHE_HOST
                valueFrom:
                  configMapKeyRef:
                    name: pastebin-config
                    key: cache_host
              - name: MYPASTEBIN_CACHE_USER
                valueFrom:
                  secretKeyRef:
                    name: redis-pastebin-credentials
                    key: username
              - name: MYPASTEBIN_CACHE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: redis-pastebin-credentials
                    key: password
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: pastebin-aws-credentials
                    key: access_key_id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: pastebin-aws-credentials
                    key: secret_access_key
