apiVersion: apps/v1
kind: Deployment
metadata:
  name: pastebin-deploy
  labels:
    app.kubernetes.io/name: pastebin
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pastebin
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pastebin
        app.kubernetes.io/component: web
    spec:
      containers:
      - name: pastebin
        image: jschnab/pastebin:async-dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: gunicorn-port
        env:
        - name: MYPASTEBIN_S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: pastebin-config
              key: s3_bucket
        - name: MYPASTEBIN_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: pastebin-config
              key: db_host
        - name: MYPASTEBIN_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: pastebin-config
              key: db_port
        - name: MYPASTEBIN_DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: pastebin-config
              key: db_database
        - name: MYPASTEBIN_DB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-pastebin-credentials
              key: username
        - name: MYPASTEBIN_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-pastebin-credentials
              key: password
        - name: MYPASTEBIN_URL
          valueFrom:
            configMapKeyRef:
              name: pastebin-config
              key: app_url
        - name: MYPASTEBIN_CACHE_HOST
          valueFrom:
            configMapKeyRef:
              name: pastebin-config
              key: cache_host
        - name: MYPASTEBIN_CACHE_USER
          valueFrom:
            secretKeyRef:
              name: redis-pastebin-credentials
              key: username
        - name: MYPASTEBIN_CACHE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-pastebin-credentials
              key: password
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: pastebin-aws-credentials
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: pastebin-aws-credentials
              key: secret_access_key
