apiVersion: v1
kind: Service
metadata:
  name: pastebin-service
  labels:
    app.kubernetes.io/name: pastebin
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/name: pastebin
