apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
spec:
  ports:
  - port: 6379
    name: redis-port
  selector:
    app.kubernetes.io/name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetest.io/version: "7.4"
        app.kubernetes.io/component: cache
    spec:
      containers:
      - name: redis
        image: redis:7.4-alpine
        ports:
        - containerPort: 6379
          name: redis-port
        volumeMounts:
        - name: config-volume
          mountPath: /etc/redis/
        resources:
          requests:
            memory: 1Gi
        command: ["redis-server", "/etc/redis/redis.conf"]
      volumes:
      - name: config-volume
        configMap:
          name: redis-config
