#!/usr/bin/env bash

set -ex

# Set a value for the following variables:
# Domain of the web application. Do not include www. for APP_DOMAIN.
APP_DOMAIN=

# Email given to Certbot.
EMAIL=


# Configure SSL certificates.
certbot \
  --nginx \
  --redirect \
  -d $APP_DOMAIN \
  -d www.$APP_DOMAIN \
  -m $EMAIL \
  --non-interactive \
  --agree-tos

certbot renew --dry-run
